# Generated by Django 2.2.14 on 2021-08-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingintvalue',
            name='field_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingtextvalue',
            name='field_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
