# Generated by Django 2.2.14 on 2021-05-11 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('week', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(choices=[('Kg', 'Kilograms'), ('P', 'plates'), ('Kg', 'Kilograms'), ('BW', 'Body Weight'), ('HD', 'Holes Down'), ('ES', 'Each Side'), ('EL', 'Each Leg')], max_length=10)),
                ('sets', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exercise', to='api.ExerciseType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
