# Generated by Django 2.2.14 on 2021-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='phase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
