# Generated by Django 2.2.14 on 2021-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercisetype_trainingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
