# Generated by Django 2.2.14 on 2021-10-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210824_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingintvalue',
            name='client',
        ),
        migrations.RemoveField(
            model_name='trackinggroup',
            name='intfields',
        ),
        migrations.DeleteModel(
            name='TrackingIntField',
        ),
        migrations.DeleteModel(
            name='TrackingIntValue',
        ),
    ]
