# Generated by Django 2.2.14 on 2021-06-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_week_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='phase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
