# Generated by Django 2.2.14 on 2021-10-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211001_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingtextfield',
            name='type',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
