# Generated by Django 2.2.14 on 2021-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210614_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingentry',
            name='phase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingentry',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
