# Generated by Django 2.2.14 on 2021-05-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trainingentry_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingentry',
            name='exercise',
        ),
    ]
