# Generated by Django 2.2.14 on 2021-10-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trackingtextfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
