# Generated by Django 2.2.14 on 2021-05-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_trainingentry_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exercise', to='api.ExerciseType'),
            preserve_default=False,
        ),
    ]
