# Generated by Django 2.2.14 on 2021-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trainingentry_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(unique=True)),
                ('sets', models.IntegerField()),
                ('reps', models.CharField(max_length=300)),
                ('weights', models.CharField(max_length=300)),
            ],
        ),
    ]
