# Generated by Django 2.2.14 on 2021-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_setfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setfeedback',
            name='training_Entry',
        ),
        migrations.AddField(
            model_name='setfeedback',
            name='t_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
