# Generated by Django 2.2.14 on 2021-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_set_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_entry',
            name='t_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set_entry',
            name='e_id',
            field=models.IntegerField(),
        ),
    ]
