# Generated by Django 2.2.14 on 2021-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211028_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setfeedback',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setfeedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
