# Generated by Django 2.2.14 on 2021-11-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211110_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
