# Generated by Django 2.2.14 on 2021-05-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='is_trainer',
        ),
    ]
