# Generated by Django 2.2.14 on 2022-01-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trainingentry_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingentry',
            options={'ordering': ['day', 'order']},
        ),
    ]
