# Generated by Django 2.2.14 on 2022-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220104_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setfeedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
