# Generated by Django 2.2.14 on 2022-02-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220131_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setfeedback',
            old_name='feedback',
            new_name='comment',
        ),
    ]
