# Generated by Django 2.2.14 on 2021-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
