# Generated by Django 2.2.14 on 2021-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210601_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
