# Generated by Django 2.2.14 on 2022-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220201_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
