# Generated by Django 2.2.14 on 2021-06-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210601_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='selected_client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Selected_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
