# Generated by Django 2.2.14 on 2021-06-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trainer_selected_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='selected_client',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Selected_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
