# Generated by Django 2.2.14 on 2022-04-21 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220217_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFitnessPal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myfitnesspal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
