# Generated by Django 2.2.14 on 2022-04-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_myfitnesspal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFitnessPalFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(blank=True, to='api.TrackingTextField')),
            ],
        ),
    ]
