# Generated by Django 2.2.14 on 2022-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_myfitnesspalfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
