# Generated by Django 2.2.14 on 2022-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_week_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfitnesspal',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
