# Generated by Django 2.2.14 on 2022-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_myfitnesspal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='inPerson',
            field=models.BooleanField(default=False),
        ),
    ]
