# Generated by Django 2.2.14 on 2021-06-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210604_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='selected_client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Selected_client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
